//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TukiVerkko1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int LoginID { get; set; }
        public string Käyttäjätunnus { get; set; }
        public string Salasana { get; set; }
        public string Rooli { get; set; }
    }
}
