//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TukiVerkko1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiketit
    {
        public int TikettiID { get; set; }
        public int AsiakasID { get; set; }
        public int KategoriaID { get; set; }
        public string Otsikko { get; set; }
        public string Kuvaus { get; set; }
        public Nullable<System.DateTime> Aika { get; set; }
        public Nullable<System.DateTime> Valmistumisaika { get; set; }
        public string Status { get; set; }
    
        public virtual Asiakkaat Asiakkaat { get; set; }
        public virtual Kategoriat Kategoriat { get; set; }
    }
}
